//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3Calc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H3Calc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Heroes xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Hero&gt;
        ///    &lt;Id&gt;0&lt;/Id&gt;
        ///    &lt;Name&gt;Оррин&lt;/Name&gt;
        ///    &lt;SpecializedSecondarySkill&gt;Archery&lt;/SpecializedSecondarySkill&gt;
        ///  &lt;/Hero&gt;
        ///  &lt;Hero&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Валеска&lt;/Name&gt;
        ///    &lt;SpecializedUnitId&gt;2&lt;/SpecializedUnitId&gt;
        ///  &lt;/Hero&gt;
        ///  &lt;Hero&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;Эдрик&lt;/Name&gt;
        ///    &lt;SpecializedUnitId&gt;4&lt;/SpecializedUnitId&gt;
        ///  &lt;/Hero&gt;
        ///  &lt;Hero&gt;
        ///    &lt;Id&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string heroes {
            get {
                return ResourceManager.GetString("heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Terrains xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;0&lt;/Id&gt;
        ///    &lt;Name&gt;Dirt&lt;/Name&gt;
        ///  &lt;/Terrain&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Sand&lt;/Name&gt;
        ///  &lt;/Terrain&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;Grass&lt;/Name&gt;
        ///  &lt;/Terrain&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;3&lt;/Id&gt;
        ///    &lt;Name&gt;Snow&lt;/Name&gt;
        ///  &lt;/Terrain&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;4&lt;/Id&gt;
        ///    &lt;Name&gt;Swamp&lt;/Name&gt;
        ///  &lt;/Terrain&gt;
        ///  &lt;Terrain&gt;
        ///    &lt;Id&gt;5&lt;/Id&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terrains {
            get {
                return ResourceManager.GetString("terrains", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unit_portraits {
            get {
                object obj = ResourceManager.GetObject("unit_portraits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Units xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Unit&gt;
        ///    &lt;Id&gt;0&lt;/Id&gt;
        ///    &lt;Name&gt;Копейщик&lt;/Name&gt;
        ///    &lt;Level&gt;1&lt;/Level&gt;
        ///    &lt;InitialStats&gt;
        ///        &lt;Attack&gt;4&lt;/Attack&gt;
        ///        &lt;Defense&gt;5&lt;/Defense&gt;
        ///        &lt;MinDamage&gt;1&lt;/MinDamage&gt;
        ///        &lt;MaxDamage&gt;3&lt;/MaxDamage&gt;
        ///        &lt;Health&gt;10&lt;/Health&gt;
        ///    &lt;/InitialStats&gt;
        ///    &lt;NativeTerrainId&gt;2&lt;/NativeTerrainId&gt;
        ///  &lt;/Unit&gt;
        ///  &lt;Unit&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Алеб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
    }
}
